keycloak:
  image: quay.io/keycloak/keycloak:24.0.1
  command: start-dev --import-realm
  environment:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
  volumes:
    - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
  ports:
    - "8080:8080"
